## Project information
site_name: Caleb Dame Portfolio
site_url: https://calebdame.com
site_description: Caleb Dame Website

## Repository
repo_name: github.com/calebdame
repo_url: https://github.com/calebdame
edit_uri: ''  #disables edit button

## Social Media
extra:
  social:
    # - icon: fontawesome/solid/house
    #   link: https://up42.com
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/up42_
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/up42/
    - icon: fontawesome/brands/github-alt
      link: https://github.com/calebdame
    # - icon: fontawesome/brands/docker
    #   link: https://hub.docker.com/u/up42
    - icon: fontawesome/solid/envelope
      link: mailto:calebdame@gmail.com

## Page tree
nav:
    - Home: index.md
    - Projects:
      - Overview: projects.md
      - Battleship Solvers: battleship.md
      - Fake Tweet Generation: twitter.md
      - An LSTMozart: music.md
    - Papers:
        - Overview: papers.md
        - Causal Models in the Case of Infinite Variance: inf_var.md
        - Portfolio Optimization Via Optimal Control: optimal_control.md
        - Feature Selection for Causal Analysis in Stop and Frisk Dataset: NYC.md
        - A Survey of Time-Series Weather Prediction Models: weather.md 
        - Emotion Classification in Audio: audio.md 
        - The Effect of No-Fault Insurance on Auto Insurance Premiums: no_fault.md 
    - Resume: resume.md
    - About Me: calebdame.md

## Configuration
theme:
  name: material
  custom_dir: docs/theme_override_home/
  # 404 page
  static_templates:
    - 404.html
  # Don't include MkDocs' JavaScript 
  include_search_page: false
  search_index_only: true
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.expand
  palette:
    primary: orange
    accent: deep-orange
  font:
    text: Roboto
    code: Roboto Mono
  icon:  # from .icons path. Add to theme override for custom logo.
    logo: python-logo  # top left header logo
  favicon: assets/btclogo.ico #browser tab logo

## Plugins
plugins:
  - search
  - autolinks

## Custom theme additions
extra_javascript:
        - 'stylesheets/extra.js'
extra_css:
        - stylesheets/extra.css

## Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.md_in_html
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      baselevel: 1
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

